name: nl_transport_pulse
version: '1.0.0'

profile: nl_transport_pulse

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  is_test_run: false

models:
  nl_transport_pulse:
    staging:
      +materialized: view
      +schema: staging_nl_transport
    intermediate:
      +materialized: table
      +schema: staging_nl_transport
    core:
      +materialized: table
      +schema: core_nl_transport

seeds:
  nl_transport_pulse:
    +schema: raw_nl_transport

snapshots:
  nl_transport_pulse:
    +schema: core_nl_transport
